#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)

for i in orig cn cn_input dev dev_cn dev_cn_input
do
    echo -e "\n\n========== Building tinyclub/cloud-ubuntu of $i ==========\n\n"

    ${TOP_DIR}/build $i
done
