#!/bin/bash

FEATURE=base
FEATUREFILE=${TOP_DIR}/feature
CONTAINERFILE=${TOP_DIR}/container

if [ -n "$1" ]; then
    FEATURE=$1
    DOCKERFILE=${TOP_DIR}/dockerfiles/Dockerfile.${FEATURE}
    if [ -f $DOCKERFILE ]; then
        echo $FEATURE > $FEATUREFILE
    else
        FEATURE=base
    fi
else
    [ -f $FEATUREFILE ] && FEATURE=$(< $FEATUREFILE)
    [ -z "$FEATURE" ] && FEATURE=base

    DOCKERFILE=${TOP_DIR}/dockerfiles/Dockerfile.${FEATURE}
fi

CORE_NAME=$(< ${TOP_DIR}/name)

if [ "$FEATURE" == "base" ]; then
    IMAGE_NAME=${CORE_NAME}
else
    IMAGE_NAME=${CORE_NAME}-${FEATURE}
fi

VNC_PORT=6080
SSH_PORT=22
WEBSSH_PORT=443

LOCAL_VNC_PORT=6080
LOCAL_SSH_PORT=2222
LOCAL_WEBSSH_PORT=4433

PORT_OFFSET=0

if [ -n "$RUN" -a "$RUN"=="1" ]; then 
    RETRY_COUNT=0
    while :;
    do
        [ -z "$LOCAL_VNC_PORT" -o $RETRY_COUNT -ne 0 ] && PORT_OFFSET=$((RANDOM%300)) && LOCAL_VNC_PORT=$((LOCAL_VNC_PORT+PORT_OFFSET))
        # echo "LOG: OUR PORT: $LOCAL_VNC_PORT, PORT_OFFSET=$PORT_OFFSET"
    
        ports=`docker ps -a --format="{{.Ports}}" | tr ',' '\n' | grep ":" | cut -d':' -f2 | cut -d'-' -f1 | sort -u | tr '\n' ' '`
        # [ -n "$ports" ] && echo "LOG: OLD PORTS: $ports"

        CONTAINER_NAME=$(basename $IMAGE_NAME)-${LOCAL_VNC_PORT}
        exist=`docker ps -q --filter=name=$CONTAINER_NAME | wc -l`
        [ $exist -eq 1 ] && RETRY_COUNT=2 && continue

        RETRY_COUNT=1
        for port in $ports; do [ $LOCAL_VNC_PORT -eq $port ] && RETRY_COUNT=2 && break; done
    
        [ $RETRY_COUNT -eq 1 ] && break
        # echo "LOG: Retry $RETRY_COUNT to get a unique port"
    done

    echo $CONTAINER_NAME > $CONTAINERFILE
else
    [ -f $CONTAINERFILE ] && CONTAINER_NAME=$(< $CONTAINERFILE)
    ((PORT_OFFSET=${CONTAINER_NAME##*-}-LOCAL_VNC_PORT))
    LOCAL_VNC_PORT=$((LOCAL_VNC_PORT+PORT_OFFSET))
fi

# Override CONTAINER_NAME with env
[ -n "$CONTAINER" ] && CONTAINER_NAME=$CONTAINER

echo "CONTAINER: $CONTAINER_NAME"

LOCAL_SSH_PORT=$((LOCAL_SSH_PORT+PORT_OFFSET))
LOCAL_WEBSSH_PORT=$((LOCAL_WEBSSH_PORT+PORT_OFFSET))

echo "PORTS: VNC=$LOCAL_VNC_PORT SSH=$LOCAL_SSH_PORT WEBSSH=$LOCAL_WEBSSH_PORT"
DEFAULT_PORT_MAP=" -p $LOCAL_VNC_PORT:$VNC_PORT -p $LOCAL_SSH_PORT:$SSH_PORT -p $LOCAL_WEBSSH_PORT:$WEBSSH_PORT "
