#!/bin/bash

FEATURE=base
FEATUREFILE=${TOP_DIR}/feature
CONTAINERFILE=${TOP_DIR}/container

# debug with DEBUG=1
[ x$DEBUG = x"1" ] && set -x

if [ -n "$1" ]; then
    FEATURE=$1
    DOCKERFILE=${TOP_DIR}/dockerfiles/Dockerfile.${FEATURE}
    if [ -f $DOCKERFILE ]; then
        echo $FEATURE > $FEATUREFILE
    else
        FEATURE=base
    fi
else
    [ -f $FEATUREFILE ] && FEATURE=$(< $FEATUREFILE)
    [ -z "$FEATURE" ] && FEATURE=base

    DOCKERFILE=${TOP_DIR}/dockerfiles/Dockerfile.${FEATURE}
fi

CORE_NAME=$(< ${TOP_DIR}/name)
[ -z "$HOST_NAME" ] && HOST_NAME=$(< ${TOP_DIR}/host)

if [ "$FEATURE" == "base" ]; then
    IMAGE_NAME=${CORE_NAME}
else
    IMAGE_NAME=${CORE_NAME}-${FEATURE}
fi

LOG=1
CMD=`basename $0`

echo "build pull push" | grep -q $CMD
[ $? -eq 0 ] && LOG=0

if [ "$CMD" == "run" ]; then
    while :;
    do
        CONTAINER_NAME=$(basename $IMAGE_NAME)-$RANDOM
        exist=`docker ps -q --filter=name=$CONTAINER_NAME | wc -l`
        [ $exist -eq 0 ] && break
    done

    echo $CONTAINER_NAME > $CONTAINERFILE
else
    [ -f $CONTAINERFILE ] && CONTAINER_NAME=$(< $CONTAINERFILE)
fi

# Override CONTAINER_NAME with env
[ -n "$CONTAINER" ] && CONTAINER_NAME=$CONTAINER

[ $LOG -eq 1 ] && echo "CONTAINER: $CONTAINER_NAME"

[ -z "$UNIX_USER" ] && UNIX_USER=ubuntu
[ -z "$UNIX_PWD" ] && UNIX_PWD=ubuntu
[ -z "$VNC_PWD" ] && VNC_PWD=ubuntu

[ -z "$VNC_PORT" ] && VNC_PORT=6080
[ -z "$SSH_PORT" ] && SSH_PORT=22
[ -z "$WEBSSH_PORT" ] && WEBSSH_PORT=443

[ -z "$LOCAL_VNC_PORT" ] && LOCAL_VNC_PORT=6080
[ -z "$LOCAL_SSH_PORT" ] && LOCAL_SSH_PORT=2222
[ -z "$LOCAL_WEBSSH_PORT" ] && LOCAL_WEBSSH_PORT=4433

[ -z "$LAB_SECURITY" ] && LAB_SECURITY=0

if [ $LAB_SECURITY -eq 1 ]; then
    NOSSL=0
    ENCRYPT=1
    HTTP=https
else
    NOSSL=1
    ENCRYPT=0
    HTTP=http
fi
