#!/bin/bash

FEATURE=base
FEATUREFILE=${TOP_DIR}/feature
CONTAINERFILE=${TOP_DIR}/container

if [ -n "$1" ]; then
    FEATURE=$1
    DOCKERFILE=${TOP_DIR}/dockerfiles/Dockerfile.${FEATURE}
    if [ -f $DOCKERFILE ]; then
        echo $FEATURE > $FEATUREFILE
    else
        FEATURE=base
    fi
else
    [ -f $FEATUREFILE ] && FEATURE=$(< $FEATUREFILE)
    [ -z "$FEATURE" ] && FEATURE=base

    DOCKERFILE=${TOP_DIR}/dockerfiles/Dockerfile.${FEATURE}
fi

CORE_NAME=$(< ${TOP_DIR}/name)

if [ "$FEATURE" == "base" ]; then
    IMAGE_NAME=${CORE_NAME}
else
    IMAGE_NAME=${CORE_NAME}-${FEATURE}
fi

LOG=1
CMD=`basename $0`

echo "build pull push" | grep -q $CMD
[ $? -eq 0 ] && LOG=0

if [ "$CMD" == "run" ]; then
    while :;
    do
        CONTAINER_NAME=$(basename $IMAGE_NAME)-$RANDOM
        exist=`docker ps -q --filter=name=$CONTAINER_NAME | wc -l`
        [ $exist -eq 0 ] && break
    done

    echo $CONTAINER_NAME > $CONTAINERFILE
else
    [ -f $CONTAINERFILE ] && CONTAINER_NAME=$(< $CONTAINERFILE)
fi

# Override CONTAINER_NAME with env
[ -n "$CONTAINER" ] && CONTAINER_NAME=$CONTAINER

[ $LOG -eq 1 ] && echo "CONTAINER: $CONTAINER_NAME"

VNC_PORT=6080
SSH_PORT=22
WEBSSH_PORT=443

LOCAL_VNC_PORT=6080
LOCAL_SSH_PORT=2222
LOCAL_WEBSSH_PORT=4433
