#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/../

for i in `ls ${TOP_DIR}/dockerfiles/ | sed -e "s/Dockerfile.//g"`
do
    echo -e "\n\n========== Building tinyclub/cloud-ubuntu of $i ==========\n\n"

    ${TOP_DIR}/build $i
    [ $? -ne 0 ] && exit 1
done
