#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/../

echo -e "\n\n========== Pulling tinyclub/cloud-ubuntu ==========\n\n"
docker pull tinylab/cloud-ubuntu

for i in `ls ${TOP_DIR}/dockerfiles/ | sed -e "s/Dockerfile.//g" | grep -v "^base$"`
do
    echo -e "\n\n========== Pulling tinyclub/cloud-ubuntu of $i ==========\n\n"

    docker pull tinylab/cloud-ubuntu-$i
done
