#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/..

source ${TOP_DIR}/config $*

[ -z "$HOST" ] && HOST=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_NAME`
[ -z "$PORT" ] && PORT=$SSH_PORT

ssh ubuntu@$HOST -p $PORT
