#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/..

source ${TOP_DIR}/config $*

[ -z "$ENCRYPT_CMD" ] && ENCRYPT_CMD=md5sum
[ -z "$CONTAINER_IP" ] && CONTAINER_IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_NAME`
[ -z "$PORT" ] && PORT=$LOCAL_VNC_PORT

if [ "$VNC_PORT" != "6080" ]; then
    token=`echo -n $VNC_PORT | $ENCRYPT_CMD | cut -d' ' -f1`
else
    token=`echo -n $CONTAINER_IP | $ENCRYPT_CMD | cut -d' ' -f1`
fi

URL="$HTTP://$HOST_NAME:$PORT/vnc.html?password=$VNC_PWD&autoconnect=1&token=$token&encrypt=$ENCRYPT"

echo "LOG: URL: $URL"

(chromium-browser $URL 2>&1>/dev/null &) 2>&1>/dev/null
