#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/..

source ${TOP_DIR}/config $*

[ -z "$PORT" ] && PORT=$LOCAL_VNC_PORT

if [ -n "HTTPS" -a "$HTTPS" == "0" ]; then
    URL="http://localhost:$PORT/vnc.html?password=ubuntu&autoconnect=1&encrypt=0"
else
    URL="https://localhost:$PORT/vnc.html?password=ubuntu&autoconnect=1&encrypt=1"
fi

(chromium-browser $URL 2>&1>/dev/null &) 2>&1>/dev/null
