#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/..

source ${TOP_DIR}/config $*

[ -z "$PORT" ] && PORT=$LOCAL_WEBSSH_PORT

URL=https://localhost:$PORT


# FIXME: chromium-browser doesn't support Chinese input for gateone now
# Only firefox works.
(firefox $URL 2>&1>/dev/null &) 2>&1>/dev/null
