#!/bin/bash

[ -z "$PORT" ] && PORT=4433

URL=https://localhost:$PORT


# FIXME: chromium-browser doesn't support Chinese input for gateone now
# Only firefox works.
(firefox $URL 2>&1>/dev/null &) 2>&1>/dev/null
