#!/bin/bash

TOP_DIR=$(cd $(dirname $0) && pwd)/..

source ${TOP_DIR}/config $*

[ -z "$HOST_NAME" ] && HOST_NAME=localhost
[ -z "$CONTAINER_IP" ] && CONTAINER_IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_NAME`
[ -z "$PORT" ] && PORT=$LOCAL_WEBSSH_PORT

URL="https://$HOST_NAME:$PORT/?ssh=ssh://ubuntu:ubuntu@$CONTAINER_IP:$SSH_PORT/"

echo "LOG: URL: $URL"

# FIXME: chromium-browser doesn't support Chinese input for gateone now
# Only firefox works.
(firefox $URL 2>&1>/dev/null &) 2>&1>/dev/null
