FROM tinylab/cloud-ubuntu
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

RUN apt-get -y update

# Core
RUN apt-get install -y --force-yes --no-install-recommends \
	git ca-certificates \
	make autoconf automake \
	gcc gdb gdbserver binutils \
	cscope exuberant-ctags libc6-dev \
	graphviz cflow \
	coreutils bsdutils debianutils e2fsprogs \
	ncurses-base perl-base findutils util-linux \
	diffutils patch rsync \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

RUN apt-get install -y --force-yes --no-install-recommends \
	xz-utils lzop gzip zip unzip tar \
	wget bc sed gawk \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

ADD system/dev/ /

RUN apt-get install -y --force-yes --no-install-recommends \
	ruby2.0 \
    && ruby-switch 2.0 \
    && gem install --clear-sources showterm \
    && gem cleanup \
    && rm -rf /home/ubuntu/.gem \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /home/ubuntu/

EXPOSE 6080 443 22

WORKDIR /

ENTRYPOINT ["/startup.sh"]
