FROM ubuntu:14.04.5
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

# Configure the fast DNS resolv server
ADD system/base/etc/apt/sources.list /etc/apt/sources.list
RUN /usr/sbin/service networking restart

# Setup our Ubuntu sources
ADD system/base/etc/resolv.conf /etc/resolv.conf
RUN apt-get -y update

# Core
RUN apt-get install -y --force-yes --no-install-recommends \
	supervisor \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

# Web SSH
RUN apt-get install -y --force-yes --no-install-recommends python-pip dtach \
	openssh-client \
    && pip install gateone \
    && mkdir -p /etc/gateone/ssl/ \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

# Web VNC
RUN apt-get install -y --force-yes --no-install-recommends gcc python-dev nginx \
	python-numpy \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*.deb

ADD system/web/web/requirements.txt /web-requirements.txt
RUN pip install setuptools wheel \
    && pip install -r /web-requirements.txt \
    && rm /web-requirements.txt

# For gateone invalid ip check
RUN pip install netifaces

ADD system/web/ /

EXPOSE 6080 443

WORKDIR /

ENTRYPOINT ["/startup.sh"]
