FROM tinylab/cloud-ubuntu-vm_embedded_markdown
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

# RUN sed -i -e "s%mirrors.linode.com%cn.archive.ubuntu.com%g" /etc/apt/sources.list

RUN apt-get -y update

RUN apt-get install -y --force-yes --no-install-recommends \
	ruby2.0-dev \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*.deb

# RUN sed -i -e "s%cn.archive.ubuntu.com%mirrors.linode.com%g" /etc/apt/sources.list

RUN gem install --clear-sources iconv jekyll jekyll-paginate jekyll-sitemap bundler pygments.rb \
    && gem cleanup \
    && rm -rf /home/ubuntu/.gem

ADD system/jekyll/ /

EXPOSE 8080 6080 443 22

WORKDIR /

ENTRYPOINT ["/startup.sh"]
