FROM tinylab/cloud-ubuntu
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

ADD system/proxy_server/ /

EXPOSE 80

WORKDIR /

ENTRYPOINT ["/startup.sh"]
