FROM tinylab/cloud-ubuntu
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

RUN apt-get -y update

# Core
RUN apt-get install -y --force-yes --no-install-recommends \
	git ca-certificates \
	make gcc gdb binutils build-essential \
	cscope exuberant-ctags libc6-dev \
	graphviz cflow \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

RUN apt-get install -y --force-yes --no-install-recommends \
	xz-utils wget unzip bc \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

ADD tools/dev/ruby-switch /
RUN apt-get install -y --force-yes --no-install-recommends \
	ruby2.0 \
    && /ruby-switch 2.0 \
    && rm /ruby-switch \
    && gem install --clear-sources showterm \
    && gem cleanup \
    && rm -rf /home/ubuntu/.gem \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

RUN rm -rf /var/lib/apt/lists/*

EXPOSE 6080 443 22

WORKDIR /

ENTRYPOINT ["/startup.sh"]
