FROM tinylab/cloud-ubuntu
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

ADD system/tproxy_client/ /

EXPOSE 6080 443 22

WORKDIR /

ENTRYPOINT ["/startup.sh"]
