FROM tinylab/cloud-ubuntu
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

RUN apt-get -y update

RUN apt-get install -y --force-yes --no-install-recommends \
	openssh-client sshpass \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*.deb

ADD system/reverse_proxy/ /

EXPOSE 5900 22

WORKDIR /

ENTRYPOINT ["/startup.sh"]
